packageExtensions:
  debug@>=3.0.0:
    dependencies:
      supports-color: ^9.0.0
  vite@*:
    dependencies:
      supports-color: ^9.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.1.cjs
